from __future__ import annotations

from decimal import Decimal

from sqlalchemy.orm import Session

from app.models.payroll_salary_structure import PayrollConcept, PayrollItem
from app.services.payroll_amounts import money

ENGINE_SOURCE_KEY_PREFIX = "ENGINE"


def concept_values_from_line(line: dict) -> dict:
    return {
        "name": line["name"],
        "category": line.get("category") or "OTRO",
        "concept_type": line.get("concept_type") or "DEVENGO",
        "salary_nature": line.get("salary_nature") or "SALARIAL",
        "source_type": line.get("source_type") or "SYSTEM",
        "calculation_type": "FIXED_AMOUNT",
        "default_amount": Decimal("0.00"),
        "default_unit_price": Decimal("0.00"),
        "applies_workday_percentage": False,
        "is_system": True,
        "is_taxable": bool(line.get("is_taxable")),
        "is_contribution_base": bool(line.get("is_contribution_base")),
        "affects_gross": bool(line.get("affects_gross")),
        "affects_net": bool(line.get("affects_net")),
        "formula": line.get("formula"),
        "is_active": True,
        "display_order": int(line.get("display_order") or 0),
        "notes": "Concepto canónico generado por el motor central de nómina.",
    }


def ensure_engine_concept(db: Session, line: dict) -> PayrollConcept:
    code = str(line["code"]).upper()[:120]
    concept = db.query(PayrollConcept).filter(PayrollConcept.code == code).first()
    values = concept_values_from_line(line)
    if concept is None:
        concept = PayrollConcept(code=code, **values)
        db.add(concept)
        db.flush()
        return concept

    for key, value in values.items():
        setattr(concept, key, value)
    return concept


def sync_engine_concept_items(db: Session, payroll_id: int, lines: list[dict]) -> dict[str, int]:
    """Replace canonical engine lines for a payroll without touching manual lines.

    Lines generated by incidents, proration or seniority keep their own source
    keys. This function owns only keys prefixed as ENGINE:{payroll_id}:...
    """

    prefix = f"{ENGINE_SOURCE_KEY_PREFIX}:{payroll_id}:"
    existing = (
        db.query(PayrollItem)
        .filter(PayrollItem.payroll_id == payroll_id, PayrollItem.source_key.like(f"{prefix}%"))
        .all()
    )
    for item in existing:
        db.delete(item)
    db.flush()

    created = 0
    for line in lines:
        amount = money(line.get("amount"))
        code = str(line["code"]).upper()[:120]
        concept = ensure_engine_concept(db, {**line, "code": code})
        source_key = f"{prefix}{code}"
        db.add(
            PayrollItem(
                payroll_id=payroll_id,
                concept_id=concept.id,
                description=line.get("description") or line.get("name"),
                quantity=money(line.get("quantity") or Decimal("1.00")),
                unit_price=money(line.get("unit_price") if line.get("unit_price") is not None else amount),
                amount=amount,
                display_order=int(line.get("display_order") or concept.display_order or 0),
                notes=line.get("formula"),
                source_type=str(line.get("source_type") or "SYSTEM").lower(),
                source_key=source_key,
                is_automatic=True,
                calculation_trace=line.get("trace") or {},
            )
        )
        created += 1

    db.flush()
    return {"deleted_items": len(existing), "created_items": created}
