const cssVar = (name) => `var(${name})`;

export const designTokens = Object.freeze({
  color: Object.freeze({
    canvas: cssVar("--an-color-canvas"),
    surface: cssVar("--an-color-surface"),
    surfaceSubtle: cssVar("--an-color-surface-subtle"),
    surfaceMuted: cssVar("--an-color-surface-muted"),
    overlay: cssVar("--an-color-overlay"),
    textPrimary: cssVar("--an-color-text-primary"),
    textSecondary: cssVar("--an-color-text-secondary"),
    textMuted: cssVar("--an-color-text-muted"),
    textDisabled: cssVar("--an-color-text-disabled"),
    textInverse: cssVar("--an-color-text-inverse"),
    border: cssVar("--an-color-border"),
    borderStrong: cssVar("--an-color-border-strong"),
    primary: cssVar("--an-color-action-primary"),
    primaryHover: cssVar("--an-color-action-primary-hover"),
    secondary: cssVar("--an-color-action-secondary"),
    brand: cssVar("--an-color-brand-500"),
    success: cssVar("--an-color-success-600"),
    warning: cssVar("--an-color-warning-500"),
    danger: cssVar("--an-color-danger-600"),
    info: cssVar("--an-color-info-600"),
  }),
  space: Object.freeze({
    0: cssVar("--an-space-0"),
    1: cssVar("--an-space-1"),
    2: cssVar("--an-space-2"),
    3: cssVar("--an-space-3"),
    4: cssVar("--an-space-4"),
    5: cssVar("--an-space-5"),
    6: cssVar("--an-space-6"),
    8: cssVar("--an-space-8"),
    10: cssVar("--an-space-10"),
    12: cssVar("--an-space-12"),
    16: cssVar("--an-space-16"),
    20: cssVar("--an-space-20"),
    24: cssVar("--an-space-24"),
  }),
  radius: Object.freeze({
    sm: cssVar("--an-radius-sm"),
    md: cssVar("--an-radius-md"),
    lg: cssVar("--an-radius-lg"),
    xl: cssVar("--an-radius-xl"),
    pill: cssVar("--an-radius-pill"),
  }),
  shadow: Object.freeze({
    none: cssVar("--an-shadow-none"),
    xs: cssVar("--an-shadow-xs"),
    sm: cssVar("--an-shadow-sm"),
    md: cssVar("--an-shadow-md"),
    lg: cssVar("--an-shadow-lg"),
  }),
  controlHeight: Object.freeze({
    sm: cssVar("--an-control-height-sm"),
    md: cssVar("--an-control-height-md"),
    lg: cssVar("--an-control-height-lg"),
    xl: cssVar("--an-control-height-xl"),
  }),
  layout: Object.freeze({
    sidebarWidth: cssVar("--an-sidebar-width"),
    topbarHeight: cssVar("--an-topbar-height"),
    contentMaxWidth: cssVar("--an-content-max-width"),
    pagePaddingInline: cssVar("--an-page-padding-inline"),
    pagePaddingBlock: cssVar("--an-page-padding-block"),
  }),
  motion: Object.freeze({
    fast: cssVar("--an-duration-fast"),
    normal: cssVar("--an-duration-normal"),
    slow: cssVar("--an-duration-slow"),
    easing: cssVar("--an-ease-standard"),
  }),
});

export default designTokens;
