"""Catálogo educativo de claves CRA basado en la Tabla 84 (julio de 2026)."""

CRA_CODES = [
    {"code": "0001", "name": "Retribución no incluida en otros apartados", "allowed_indicators": ["I"]},
    {"code": "0002", "name": "Horas extraordinarias", "allowed_indicators": ["I"]},
    {"code": "0003", "name": "Horas extraordinarias fuerza mayor", "allowed_indicators": ["I"]},
    {"code": "0004", "name": "Prorrateo de pagas extraordinarias", "allowed_indicators": ["I"]},
    {"code": "0005", "name": "Otras retribuciones de vencimiento superior al mensual", "allowed_indicators": ["I"]},
    {"code": "0006", "name": "Vacaciones retribuidas no disfrutadas tras fin de contrato", "allowed_indicators": ["I"]},
    {"code": "0007", "name": "Salarios de tramitación", "allowed_indicators": ["I"]},
    {"code": "0008", "name": "Atrasos no incluidos en otros apartados", "allowed_indicators": ["I"]},
    {"code": "0009", "name": "Atrasos por convenio colectivo", "allowed_indicators": ["I"]},
    {"code": "0010", "name": "Atrasos por sentencia judicial", "allowed_indicators": ["I"]},
    {"code": "0011", "name": "Atrasos por normativa", "allowed_indicators": ["I"]},
    {"code": "0012", "name": "Atrasos por acta de conciliación", "allowed_indicators": ["I"]},
    {"code": "0013", "name": "Retribución en especie no incluida en otros apartados", "allowed_indicators": ["I"]},
    {"code": "0014", "name": "Vivienda propiedad pagador con valor catastral", "allowed_indicators": ["I", "E"]},
    {"code": "0015", "name": "Vivienda propiedad pagador pendiente valor catastral", "allowed_indicators": ["I", "E"]},
    {"code": "0016", "name": "Vivienda no propiedad del pagador", "allowed_indicators": ["I"]},
    {"code": "0017", "name": "Vehículo entregado al trabajador", "allowed_indicators": ["I"]},
    {"code": "0018", "name": "Uso de vehículo propiedad del pagador", "allowed_indicators": ["I"]},
    {"code": "0019", "name": "Uso de vehículo no propiedad del pagador", "allowed_indicators": ["I", "E"]},
    {"code": "0020", "name": "Uso y posterior entrega de vehículo", "allowed_indicators": ["I", "E"]},
    {"code": "0021", "name": "Préstamo con interés inferior al legal", "allowed_indicators": ["I"]},
    {"code": "0022", "name": "Manutención en especie y similares", "allowed_indicators": ["I"]},
    {"code": "0023", "name": "Hospedaje en especie y similares", "allowed_indicators": ["I"]},
    {"code": "0024", "name": "Viajes en especie y similares", "allowed_indicators": ["I"]},
    {"code": "0025", "name": "Gastos de estudios y manutención en especie", "allowed_indicators": ["I"]},
    {"code": "0026", "name": "Derechos de fundadores de sociedades", "allowed_indicators": ["I"]},
    {"code": "0027", "name": "Quebranto de moneda", "allowed_indicators": ["I"]},
    {"code": "0028", "name": "Desgaste de útiles y herramientas", "allowed_indicators": ["I"]},
    {"code": "0029", "name": "Adquisición y mantenimiento de ropa de trabajo", "allowed_indicators": ["I", "E"]},
    {"code": "0030", "name": "Percepciones por matrimonio", "allowed_indicators": ["I"]},
    {"code": "0031", "name": "Donaciones promocionales", "allowed_indicators": ["I"]},
    {"code": "0032", "name": "Pluses de transporte y distancia", "allowed_indicators": ["I"]},
    {"code": "0033", "name": "Planes de pensiones y sistemas alternativos", "allowed_indicators": ["I"]},
    {"code": "0034", "name": "Acciones o participaciones de empresa", "allowed_indicators": ["I"]},
    {"code": "0035", "name": "Gastos de estudio, capacitación o reciclaje", "allowed_indicators": ["E"]},
    {"code": "0036", "name": "Cantinas y comedores económicos", "allowed_indicators": ["I"]},
    {"code": "0037", "name": "Bienes destinados a servicios sociales y culturales", "allowed_indicators": ["I"]},
    {"code": "0038", "name": "Primas seguro AT o responsabilidad civil", "allowed_indicators": ["I"]},
    {"code": "0039", "name": "Primas seguro enfermedad común trabajador", "allowed_indicators": ["I"]},
    {"code": "0040", "name": "Primas seguro enfermedad común familiar", "allowed_indicators": ["I"]},
    {"code": "0041", "name": "Prestación de educación a hijos de trabajadores", "allowed_indicators": ["I", "E"]},
    {"code": "0042", "name": "Gastos de estancia", "allowed_indicators": ["I", "E"]},
    {"code": "0043", "name": "Manutención con pernocta en España", "allowed_indicators": ["I", "E"]},
    {"code": "0044", "name": "Manutención con pernocta en extranjero", "allowed_indicators": ["I", "E"]},
    {"code": "0045", "name": "Manutención sin pernocta en España", "allowed_indicators": ["I", "E"]},
    {"code": "0046", "name": "Manutención sin pernocta en extranjero", "allowed_indicators": ["I", "E"]},
    {"code": "0047", "name": "Manutención personal de vuelo en España", "allowed_indicators": ["I", "E"]},
    {"code": "0048", "name": "Manutención personal de vuelo en extranjero", "allowed_indicators": ["I", "E"]},
    {"code": "0049", "name": "Locomoción en transporte público", "allowed_indicators": ["E"]},
    {"code": "0050", "name": "Locomoción sin justificación del importe", "allowed_indicators": ["I", "E"]},
    {"code": "0051", "name": "Indemnización por fallecimiento", "allowed_indicators": ["I", "E"]},
    {"code": "0052", "name": "Indemnización por traslado", "allowed_indicators": ["I", "E"]},
    {"code": "0053", "name": "Indemnización por suspensión", "allowed_indicators": ["I", "E"]},
    {"code": "0054", "name": "Indemnización por despido o falta de preaviso", "allowed_indicators": ["I", "E"]},
    {"code": "0055", "name": "Mejora de prestación por incapacidad temporal", "allowed_indicators": ["E"]},
    {"code": "0056", "name": "Mejoras de prestaciones distintas de IT", "allowed_indicators": ["I"]},
    {"code": "0057", "name": "Horas complementarias pactadas", "allowed_indicators": ["I"]},
    {"code": "0058", "name": "Horas complementarias voluntarias", "allowed_indicators": ["I"]},
    {"code": "0059", "name": "Vacaciones no disfrutadas tras fallecimiento", "allowed_indicators": ["I"]},
    {"code": "0060", "name": "Vacaciones no disfrutadas cotizadas durante el contrato", "allowed_indicators": ["I"]},
    {"code": "0061", "name": "Transporte colectivo aportado por la empresa", "allowed_indicators": ["I"]},
    {"code": "0062", "name": "Gastos de teletrabajo", "allowed_indicators": ["E"]},
]

CRA_CODE_BY_VALUE = {item["code"]: item for item in CRA_CODES}
