export const EDUCATION_LEVEL_OPTIONS = [
  "Sin estudios",
  "Estudios primarios incompletos",
  "Estudios primarios completos",
  "1ª etapa estudios secundarios sin título",
  "Graduado escolar o equivalente",
  "Formación Profesional Grado Medio",
  "Bachiller, BUP y equivalente",
  "Formación Profesional Grado Superior",
  "Diplomados, licenciados y equivalentes",
  "Estudios univ. oficiales de grado y de máster",
];

export const initialEmployeeForm = {
  employee_code: "",
  company_id: "",
  center_id: "",
  document_type: "DNI",
  dni: "",
  nie_prefix: "",
  document_number: "",
  document_letter: "",
  naf: "",
  first_name: "",
  last_name: "",
  second_last_name: "",
  sex: "",
  birth_date: "",
  nationality: "",
  birth_place: "",
  domicile: "",
  address: "",
  city: "",
  province: "",
  postal_code: "",
  landline_phone: "",
  mobile_phone: "",
  phone: "",
  fax: "",
  email: "",
  website: "",
  education_level: "",
  academic_title: "",
  academic_title_date: "",
  main_profession: "",
  other_courses: "",
  accreditations: "",
  languages: "",
  representative_role: "",
  representative_nif: "",
  representative_full_name: "",
  observations: "",
};

const nullableStringFields = [
  "naf",
  "nie_prefix",
  "document_number",
  "document_letter",
  "second_last_name",
  "sex",
  "nationality",
  "birth_place",
  "domicile",
  "address",
  "city",
  "province",
  "postal_code",
  "landline_phone",
  "mobile_phone",
  "phone",
  "fax",
  "email",
  "website",
  "education_level",
  "academic_title",
  "main_profession",
  "other_courses",
  "accreditations",
  "languages",
  "representative_role",
  "representative_nif",
  "representative_full_name",
  "observations",
];

export function buildEmployeePayload(form) {
  const domicile = form.domicile || form.address || null;
  const payload = {
    ...form,
    document_type: form.document_type || "DNI",
    company_id: form.company_id ? Number(form.company_id) : null,
    center_id: form.center_id ? Number(form.center_id) : null,
    birth_date: form.birth_date || null,
    academic_title_date: form.academic_title_date || null,
    domicile,
    address: domicile,
    phone: null,
    is_active: form.is_active ?? true,
  };

  nullableStringFields.forEach((field) => {
    payload[field] = payload[field] || null;
  });

  return payload;
}
