"""Especificaciones pedagógicas de las 60 prácticas del Temario Maestro 2026.

Este archivo completa la Fase A. No contiene todavía datos demo ni reglas ORM:
define qué debe aprender el alumno y qué evidencia tendrá que producir la Fase B.
"""

from __future__ import annotations

from typing import Any


def _spec(
    objective: str,
    *,
    prerequisites: list[str],
    situation: str,
    inputs: list[str],
    expected_actions: list[str],
    criteria: list[str],
    theory: list[str],
    feedback: list[str],
) -> dict[str, Any]:
    return {
        "learning_objective": objective,
        "prerequisites": prerequisites,
        "professional_situation": situation,
        "student_inputs": inputs,
        "expected_actions": expected_actions,
        "evaluation_criteria": criteria,
        "theory_topics": theory,
        "feedback_if_failed": feedback,
    }


ACTIVITY_SPECS_2026: dict[str, dict[str, Any]] = {
    "A01": _spec(
        "Reconocer cuándo un supuesto reúne los elementos básicos de una relación laboral por cuenta ajena.",
        prerequisites=[],
        situation="Se reciben varios supuestos de prestación de servicios y debe decidirse cuáles pertenecen al ámbito laboral ordinario.",
        inputs=["Descripción de la prestación", "Dependencia y ajenidad", "Voluntariedad y retribución"],
        expected_actions=["Clasificar cada supuesto", "Justificar la decisión con los elementos observados"],
        criteria=["Distingue relación laboral, relación especial y supuesto excluido", "No basa la respuesta solo en el nombre del contrato"],
        theory=["Elementos de la relación laboral", "Ámbito de aplicación del Estatuto de los Trabajadores"],
        feedback=["Revisa si existen voluntariedad, retribución, ajenidad y dependencia", "Comprueba si el supuesto está expresamente excluido o sometido a relación especial"],
    ),
    "A02": _spec(
        "Preparar la estructura mínima de empresa y centro necesaria para operar con trabajadores.",
        prerequisites=["A01"],
        situation="Una empresa comienza a utilizar AulaNomina y necesita disponer de su estructura administrativa básica antes de contratar.",
        inputs=["Razón social", "CIF", "CCC", "Centro de trabajo", "Datos de contacto"],
        expected_actions=["Crear o revisar la empresa", "Crear o revisar el centro", "Relacionar correctamente centro y empresa"],
        criteria=["Empresa identificada sin duplicados", "Centro adscrito a la empresa correcta", "Datos esenciales disponibles para procesos posteriores"],
        theory=["Empresario y centro de trabajo", "Inscripción y datos de cotización como contexto administrativo"],
        feedback=["Comprueba que el centro pertenece a la empresa del caso", "Revisa identificadores y datos administrativos obligatorios"],
    ),
    "A03": _spec(
        "Relacionar un trabajador con el convenio colectivo aplicable y entender qué variables condiciona.",
        prerequisites=["A02"],
        situation="La empresa dispone de más de un convenio y debe determinarse cuál afecta al puesto del trabajador.",
        inputs=["Actividad de la empresa", "Centro de trabajo", "Puesto o grupo profesional", "Convenios disponibles"],
        expected_actions=["Seleccionar el convenio", "Asignarlo al expediente", "Revisar variables salariales y de jornada relacionadas"],
        criteria=["El convenio asignado corresponde al supuesto", "El alumno identifica al menos salario, jornada o clasificación como variables relevantes"],
        theory=["Función y ámbito del convenio colectivo", "Relación entre convenio, clasificación profesional y retribución"],
        feedback=["No elijas el convenio solo por su nombre", "Contrasta ámbito y puesto antes de asignarlo"],
    ),
    "A04": _spec(
        "Crear un expediente laboral completo y coherente a partir de documentación de incorporación.",
        prerequisites=["A02"],
        situation="RRHH recibe la documentación de una nueva incorporación y debe dar de alta su expediente.",
        inputs=["Nombre y apellidos", "DNI/NIE", "NAF", "Fecha de nacimiento", "Nacionalidad", "Datos de contacto"],
        expected_actions=["Crear el trabajador", "Introducir datos identificativos", "Dejar el expediente activo"],
        criteria=["Trabajador localizado por identidad", "Datos principales coinciden con el caso", "Expediente activo"],
        theory=["Expediente laboral", "Datos administrativos necesarios para contratación y Seguridad Social"],
        feedback=["Revisa primero la identidad del trabajador", "Comprueba DNI/NIE, NAF y fecha de nacimiento antes de continuar"],
    ),
    "A05": _spec(
        "Detectar incoherencias en un expediente y corregirlas antes de que afecten a procesos posteriores.",
        prerequisites=["A04"],
        situation="Un expediente ya creado contiene datos incompletos o contradictorios con la documentación recibida.",
        inputs=["Ficha actual", "Documentación justificativa", "Listado de campos críticos"],
        expected_actions=["Comparar ficha y documentos", "Corregir campos erróneos", "Mantener la trazabilidad del expediente"],
        criteria=["Identifica los campos inconsistentes", "Corrige únicamente los datos afectados", "El expediente queda utilizable"],
        theory=["Calidad del dato laboral", "Trazabilidad documental"],
        feedback=["Compara el dato almacenado con la fuente documental", "Evita modificar campos que ya son correctos"],
    ),
    "A06": _spec(
        "Seleccionar una modalidad contractual coherente con la necesidad empresarial y la situación de la persona trabajadora.",
        prerequisites=["A01", "A04"],
        situation="La dirección comunica una necesidad de cobertura y RRHH debe elegir la modalidad antes de formalizar el contrato.",
        inputs=["Necesidad del puesto", "Duración prevista", "Causa", "Datos de la persona", "Posible finalidad formativa"],
        expected_actions=["Identificar la modalidad adecuada", "Descartar modalidades incompatibles", "Justificar la elección"],
        criteria=["Distingue indefinido, temporal y formativo", "En temporal identifica causa de producción o sustitución cuando proceda"],
        theory=["Modalidades vigentes de contratación", "Causalidad de la contratación temporal", "Contratos formativos"],
        feedback=["Empieza por decidir si la necesidad es indefinida o temporal", "Si es temporal, identifica la causa concreta antes de elegir"],
    ),
    "A07": _spec(
        "Formalizar correctamente un contrato indefinido con los datos esenciales del caso.",
        prerequisites=["A06"],
        situation="Se aprueba una incorporación estable y debe registrarse el contrato indefinido.",
        inputs=["Trabajador", "Fecha de inicio", "Jornada", "Puesto", "Convenio"],
        expected_actions=["Crear contrato indefinido", "Informar fecha y jornada", "Activar la relación contractual"],
        criteria=["Contrato activo", "Modalidad indefinida", "Fecha y jornada coherentes"],
        theory=["Contrato indefinido", "Forma y contenido básico del contrato"],
        feedback=["Revisa modalidad y estado contractual", "Comprueba la fecha de efectos y la jornada"],
    ),
    "A08": _spec(
        "Formalizar un contrato temporal identificando y documentando una causa válida.",
        prerequisites=["A06"],
        situation="Existe una necesidad temporal por circunstancias de la producción y debe justificarse en el contrato.",
        inputs=["Causa de temporalidad", "Duración", "Fecha de inicio", "Jornada", "Trabajador"],
        expected_actions=["Crear contrato temporal", "Informar la causa", "Definir duración y jornada"],
        criteria=["Modalidad temporal coherente", "Causa informada", "Duración compatible con el supuesto"],
        theory=["Contratación de duración determinada", "Circunstancias de la producción"],
        feedback=["Un contrato temporal necesita una causa concreta", "Revisa si la duración corresponde a la necesidad descrita"],
    ),
    "A09": _spec(
        "Registrar una sustitución vinculando correctamente la persona sustituida y la causa.",
        prerequisites=["A06", "A04"],
        situation="Una persona trabajadora causa una ausencia con reserva del puesto y se incorpora una sustituta.",
        inputs=["Persona sustituta", "Persona sustituida", "Causa", "Fecha de inicio", "Jornada"],
        expected_actions=["Crear contrato de sustitución", "Vincular persona sustituida", "Informar causa y fecha"],
        criteria=["Contrato de sustitución activo", "Persona sustituida correcta", "Fecha y causa coherentes"],
        theory=["Contrato de sustitución", "Reserva del puesto de trabajo"],
        feedback=["Comprueba quién origina la sustitución", "No confundas a la persona sustituta con la sustituida"],
    ),
    "A10": _spec(
        "Identificar y registrar los elementos administrativos propios de la formación en alternancia.",
        prerequisites=["A06"],
        situation="La empresa incorpora a una persona combinando actividad laboral retribuida y formación.",
        inputs=["Programa formativo", "Centro o entidad formativa", "Tutoría", "Jornada y tiempo formativo", "Duración"],
        expected_actions=["Seleccionar formación en alternancia", "Registrar datos formativos", "Vincular documentación del plan"],
        criteria=["Modalidad correcta", "Datos formativos esenciales presentes", "Coherencia entre actividad laboral y formación"],
        theory=["Contrato de formación en alternancia", "Plan formativo y tutoría"],
        feedback=["Este contrato no se completa solo con datos laborales", "Revisa plan formativo, tutoría y distribución de tiempos"],
    ),
    "A11": _spec(
        "Registrar un contrato formativo para la obtención de práctica profesional y comprobar sus requisitos.",
        prerequisites=["A06"],
        situation="Una persona titulada se incorpora para adquirir práctica profesional adecuada a su nivel de estudios.",
        inputs=["Titulación", "Fecha de obtención", "Puesto", "Duración", "Plan formativo individual"],
        expected_actions=["Seleccionar práctica profesional", "Registrar titulación y fechas", "Vincular plan formativo"],
        criteria=["Modalidad correcta", "Titulación y temporalidad justificadas", "Datos formativos registrados"],
        theory=["Contrato formativo para la obtención de práctica profesional", "Requisitos temporales y formativos"],
        feedback=["Verifica primero la titulación y su fecha", "Comprueba que el puesto guarda relación con la práctica profesional prevista"],
    ),
    "A12": _spec(
        "Modificar una jornada contractual sin perder el histórico de la relación laboral.",
        prerequisites=["A07"],
        situation="Empresa y trabajador acuerdan una variación de jornada con efectos desde una fecha determinada.",
        inputs=["Jornada anterior", "Nueva jornada", "Fecha de efectos", "Motivo"],
        expected_actions=["Registrar modificación", "Conservar situación anterior", "Aplicar fecha de efectos"],
        criteria=["Nueva jornada vigente desde la fecha indicada", "Histórico anterior preservado"],
        theory=["Modificación de condiciones contractuales", "Trazabilidad temporal"],
        feedback=["No sobrescribas el histórico sin fecha de efectos", "Comprueba qué jornada debe aplicarse antes y después del cambio"],
    ),
    "A13": _spec(
        "Gestionar una prórroga o transformación contractual distinguiendo ambos procesos.",
        prerequisites=["A08", "A12"],
        situation="Un contrato temporal alcanza una fecha clave y debe decidirse si se prorroga o se transforma.",
        inputs=["Contrato actual", "Fecha fin", "Nueva situación", "Causa o decisión empresarial"],
        expected_actions=["Elegir prórroga o transformación", "Registrar nueva vigencia", "Mantener trazabilidad"],
        criteria=["Operación elegida correcta", "Fechas coherentes", "Histórico contractual conservado"],
        theory=["Prórroga contractual", "Transformación a indefinido"],
        feedback=["Prorrogar no es lo mismo que transformar", "Revisa si cambia la modalidad o únicamente la vigencia"],
    ),
    "A14": _spec(
        "Configurar la estructura retributiva básica que alimentará la nómina.",
        prerequisites=["A07", "A03"],
        situation="El contrato está creado y debe configurarse su salario conforme al puesto y convenio.",
        inputs=["Salario base", "Complementos", "Periodicidad", "Convenio"],
        expected_actions=["Asignar conceptos salariales", "Informar importes", "Activar conceptos aplicables"],
        criteria=["Salario base presente", "Complementos correctos y activos", "Importes coherentes"],
        theory=["Salario y estructura salarial", "Conceptos salariales y extrasalariales"],
        feedback=["Comprueba qué conceptos forman parte de la retribución ordinaria", "Revisa importe, periodicidad y vigencia"],
    ),
    "A15": _spec(
        "Configurar pagas extraordinarias y distinguir devengo separado de prorrata.",
        prerequisites=["A14"],
        situation="El convenio establece pagas extraordinarias y debe reflejarse correctamente su tratamiento.",
        inputs=["Número de pagas", "Periodo de devengo", "Importe o conceptos", "Prorrata sí/no"],
        expected_actions=["Configurar pagas", "Seleccionar modalidad de abono", "Revisar impacto mensual"],
        criteria=["Número y devengo correctos", "Prorrata aplicada solo cuando corresponda"],
        theory=["Gratificaciones extraordinarias", "Prorrata de pagas"],
        feedback=["Distingue devengo de fecha de pago", "Comprueba si el caso exige prorrata mensual"],
    ),
    "A16": _spec(
        "Calcular una nómina ordinaria y reconocer sus bloques principales.",
        prerequisites=["A14", "A15"],
        situation="Finaliza el mes y debe calcularse la nómina de un trabajador sin incidencias.",
        inputs=["Contrato", "Estructura salarial", "Periodo", "Perfil fiscal", "Datos de cotización"],
        expected_actions=["Generar nómina", "Revisar devengos", "Revisar deducciones y líquido"],
        criteria=["Periodo correcto", "Devengos esperados", "Deducciones calculadas", "Líquido coherente"],
        theory=["Recibo de salarios", "Devengos, deducciones y líquido"],
        feedback=["Empieza revisando los devengos antes de las deducciones", "Comprueba periodo, contrato y conceptos activos"],
    ),
    "A17": _spec(
        "Calcular correctamente el devengo cuando la relación laboral no cubre todo el mes.",
        prerequisites=["A16"],
        situation="La persona se incorpora o cesa durante el mes y la nómina debe reflejar solo el periodo correspondiente.",
        inputs=["Fecha de alta o baja", "Periodo de nómina", "Salario mensual", "Jornada"],
        expected_actions=["Calcular nómina parcial", "Revisar días devengados", "Comparar con una mensualidad completa"],
        criteria=["Número de días correcto", "Devengos proporcionales", "No se retribuyen días fuera de alta"],
        theory=["Devengo proporcional", "Alta y baja dentro del periodo"],
        feedback=["Revisa la fecha efectiva de inicio o fin", "Compara los días retribuidos con el periodo de alta"],
    ),
    "A18": _spec(
        "Comprobar la formación de la base de cotización por contingencias comunes y sus límites 2026.",
        prerequisites=["A16"],
        situation="Se revisa una nómina para verificar que la base de contingencias comunes está correctamente determinada.",
        inputs=["Retribución computable", "Prorrata de pagas", "Grupo de cotización", "Topes 2026"],
        expected_actions=["Revisar conceptos incluidos", "Comprobar base resultante", "Contrastar mínimos y máximos"],
        criteria=["Incluye conceptos computables", "Aplica prorrata cuando procede", "Respeta límites del grupo"],
        theory=["Base de contingencias comunes", "Bases mínimas y máximas 2026"],
        feedback=["No confundas bruto de nómina con base de cotización", "Comprueba prorrata y topes antes de validar"],
    ),
    "A19": _spec(
        "Distinguir la base de contingencias profesionales de la base de contingencias comunes.",
        prerequisites=["A18"],
        situation="La revisión de cotización exige explicar por qué las bases pueden diferir.",
        inputs=["Conceptos retributivos", "Horas extraordinarias si existen", "Base CC", "Base AT/EP"],
        expected_actions=["Revisar base profesional", "Identificar diferencias", "Justificar el resultado"],
        criteria=["Distingue ambas bases", "Identifica conceptos que explican diferencias"],
        theory=["Contingencias profesionales", "Base de accidentes de trabajo y enfermedades profesionales"],
        feedback=["Compara los componentes de ambas bases", "Revisa especialmente conceptos que no tienen el mismo tratamiento"],
    ),
    "A20": _spec(
        "Interpretar las aportaciones de la persona trabajadora a la Seguridad Social en la nómina.",
        prerequisites=["A18", "A19"],
        situation="Un trabajador pregunta por sus deducciones de Seguridad Social y RRHH debe comprobarlas.",
        inputs=["Bases de cotización", "Tipos 2026", "Modalidad contractual"],
        expected_actions=["Revisar cuotas de trabajador", "Relacionar cada cuota con su base", "Comprobar total deducido"],
        criteria=["Tipos aplicados a la base correcta", "Suma de deducciones coherente"],
        theory=["Aportación del trabajador", "Contingencias comunes, desempleo y formación"],
        feedback=["Comprueba qué base utiliza cada porcentaje", "Distingue aportación empresarial de deducción del trabajador"],
    ),
    "A21": _spec(
        "Comprobar que la retención IRPF de nómina coincide con el perfil fiscal y el cálculo 2026.",
        prerequisites=["A16"],
        situation="Se revisa una nómina cuyo porcentaje de retención debe justificarse.",
        inputs=["Retribución prevista", "Situación personal y familiar", "Tipo calculado", "Nómina"],
        expected_actions=["Revisar perfil fiscal", "Calcular o consultar tipo", "Comparar con retención aplicada"],
        criteria=["Tipo coherente con el cálculo 2026", "Base y cuota retenida correctas"],
        theory=["Retenciones sobre rendimientos del trabajo", "Datos personales y familiares"],
        feedback=["Revisa primero el perfil fiscal", "Comprueba que el porcentaje aplicado coincide con el vigente para el caso"],
    ),
    "A22": _spec(
        "Interpretar el líquido de nómina y diferenciarlo del coste total de empresa.",
        prerequisites=["A20", "A21"],
        situation="Dirección solicita explicar cuánto recibe la persona y cuánto cuesta realmente la contratación.",
        inputs=["Total devengado", "Deducciones", "Cuotas empresariales", "Otros costes"],
        expected_actions=["Identificar líquido", "Revisar coste empresarial", "Explicar la diferencia"],
        criteria=["No confunde bruto, líquido y coste empresa", "Cuotas empresariales quedan fuera de las deducciones del trabajador"],
        theory=["Líquido a percibir", "Coste empresarial de Seguridad Social"],
        feedback=["Separa siempre cantidades del trabajador y de la empresa", "El coste empresa no es el líquido ni el bruto"],
    ),
    "A23": _spec(
        "Registrar una IT por enfermedad común y comprobar su efecto administrativo y económico.",
        prerequisites=["A16"],
        situation="Se recibe una baja médica por contingencia común que afecta al periodo de nómina.",
        inputs=["Trabajador", "Fecha de baja", "Contingencia", "Comunicación FIE", "Periodo"],
        expected_actions=["Registrar IT", "Relacionar comunicación", "Recalcular nómina"],
        criteria=["Tipo y fecha correctos", "Incidencia vinculada al trabajador", "Nómina refleja la IT"],
        theory=["Incapacidad temporal por contingencias comunes", "Efecto en cotización y nómina"],
        feedback=["Comprueba contingencia y fecha de efectos", "No recalcules antes de registrar correctamente la incidencia"],
    ),
    "A24": _spec(
        "Registrar una IT derivada de accidente de trabajo y distinguir su tratamiento del supuesto común.",
        prerequisites=["A23"],
        situation="Un parte identifica accidente de trabajo y debe reflejarse en el expediente y la nómina.",
        inputs=["Fecha de accidente/baja", "Contingencia profesional", "Trabajador", "Periodo"],
        expected_actions=["Registrar IT profesional", "Revisar datos de contingencia", "Recalcular nómina"],
        criteria=["Contingencia profesional correctamente indicada", "Fechas coherentes", "Cálculo posterior actualizado"],
        theory=["IT por contingencias profesionales", "Diferencias frente a enfermedad común"],
        feedback=["No reutilices automáticamente la configuración de enfermedad común", "Revisa la contingencia indicada en el parte"],
    ),
    "A25": _spec(
        "Registrar un periodo de vacaciones y mantener un calendario laboral coherente.",
        prerequisites=["A04"],
        situation="Una solicitud de vacaciones ha sido aprobada y debe incorporarse al expediente.",
        inputs=["Fecha inicio", "Fecha fin", "Trabajador", "Calendario"],
        expected_actions=["Registrar vacaciones", "Comprobar solapamientos", "Actualizar situación del periodo"],
        criteria=["Periodo correcto", "Sin solapamientos incompatibles", "Trabajador correcto"],
        theory=["Vacaciones anuales", "Registro de ausencias planificadas"],
        feedback=["Comprueba el intervalo completo", "Revisa si existe otra incidencia en las mismas fechas"],
    ),
    "A26": _spec(
        "Registrar una ausencia y determinar si debe producir efecto económico.",
        prerequisites=["A16"],
        situation="Se comunica una ausencia y es necesario clasificarla antes de cerrar la nómina.",
        inputs=["Tipo de ausencia", "Fechas", "Justificación", "Regla de impacto"],
        expected_actions=["Clasificar ausencia", "Registrar incidencia", "Recalcular cuando proceda"],
        criteria=["Tipo correcto", "Fechas correctas", "Impacto económico coherente con el supuesto"],
        theory=["Ausencias y permisos", "Incidencias con y sin impacto en nómina"],
        feedback=["Primero determina la naturaleza de la ausencia", "No todas las ausencias producen el mismo efecto económico"],
    ),
    "A27": _spec(
        "Aplicar una variación de jornada y comprobar su efecto sobre la retribución del periodo.",
        prerequisites=["A12", "A16"],
        situation="Una reducción o ampliación de jornada entra en vigor durante un periodo ya preparado para nómina.",
        inputs=["Jornada anterior", "Nueva jornada", "Fecha de efecto", "Periodo de nómina"],
        expected_actions=["Registrar cambio", "Recalcular periodo", "Comparar antes y después"],
        criteria=["Cambio vigente desde la fecha correcta", "Nómina recalculada", "Diferencia explicable"],
        theory=["Variaciones contractuales", "Impacto proporcional en retribución"],
        feedback=["Comprueba desde qué día produce efectos", "Compara el porcentaje de jornada con los devengos resultantes"],
    ),
    "A28": _spec(
        "Verificar los datos de afiliación necesarios antes de preparar un movimiento en Sistema RED.",
        prerequisites=["A04"],
        situation="Antes de tramitar un alta se revisa que el expediente contiene datos suficientes y coherentes.",
        inputs=["NAF", "DNI/NIE", "Empresa/CCC", "Contrato", "Fecha"],
        expected_actions=["Revisar identidad", "Revisar NAF", "Comprobar empresa, contrato y fecha"],
        criteria=["No faltan identificadores críticos", "Datos contractuales y de afiliación son coherentes"],
        theory=["Afiliación y NAF", "Datos previos a movimientos RED"],
        feedback=["Una afiliación correcta depende del expediente previo", "Revisa NAF, empresa y fecha antes de generar el movimiento"],
    ),
    "A29": _spec(
        "Preparar un movimiento de alta coherente con el contrato y la fecha de incorporación.",
        prerequisites=["A28", "A07"],
        situation="El contrato está formalizado y debe prepararse el alta de Seguridad Social.",
        inputs=["Contrato", "Fecha de inicio", "CCC", "Trabajador"],
        expected_actions=["Generar alta", "Informar fecha", "Relacionar contrato y CCC"],
        criteria=["Movimiento de alta existente", "Fecha coincide con inicio", "Persona y empresa correctas"],
        theory=["Alta en Seguridad Social", "Sistema RED"],
        feedback=["La fecha de alta debe cuadrar con la incorporación", "Comprueba contrato y CCC asociados"],
    ),
    "A30": _spec(
        "Preparar una baja o variación de afiliación distinguiendo el tipo de movimiento.",
        prerequisites=["A29"],
        situation="Se produce un cambio que exige comunicar una baja o variación de datos.",
        inputs=["Situación anterior", "Tipo de cambio", "Fecha de efectos", "Contrato"],
        expected_actions=["Seleccionar tipo de movimiento", "Informar fecha", "Generar remesa"],
        criteria=["Movimiento correcto", "Fecha coherente", "No se utiliza alta para una variación o baja"],
        theory=["Altas, bajas y variaciones", "Gestión de afiliación en RED"],
        feedback=["Identifica qué cambia antes de generar el movimiento", "Revisa si el trabajador continúa o no de alta"],
    ),
    "A31": _spec(
        "Interpretar una comunicación FIE e identificar el trabajador, proceso y fechas relevantes.",
        prerequisites=["A28"],
        situation="La empresa recibe información del INSS a través del FIE y debe revisarla antes de actuar.",
        inputs=["Comunicación FIE", "Trabajador", "Fechas", "Tipo de proceso"],
        expected_actions=["Abrir comunicación", "Identificar afectado", "Interpretar contingencia y fechas"],
        criteria=["Comunicación marcada como revisada", "Trabajador y fechas identificados correctamente"],
        theory=["Fichero INSS Empresas", "Información de prestaciones e incidencias"],
        feedback=["Lee primero los identificadores de persona y proceso", "No registres una incidencia sin contrastar las fechas del FIE"],
    ),
    "A32": _spec(
        "Conciliar una comunicación FIE con la incidencia que representa en el expediente.",
        prerequisites=["A31", "A23"],
        situation="El FIE recibido debe quedar enlazado con la IT ya registrada o servir para detectar una discrepancia.",
        inputs=["FIE revisado", "Incidencias del trabajador", "Fechas y contingencia"],
        expected_actions=["Comparar FIE e incidencia", "Relacionarlos", "Resolver discrepancias"],
        criteria=["FIE conciliado", "Incidencia correcta vinculada", "Fechas coherentes"],
        theory=["Conciliación de información INSS", "Coherencia entre comunicaciones y expediente"],
        feedback=["Compara contingencia y fechas, no solo el nombre", "Si no coincide, corrige primero el dato erróneo"],
    ),
    "A33": _spec(
        "Generar un CRA coherente con los conceptos efectivamente abonados y revisar sus validaciones.",
        prerequisites=["A16"],
        situation="Tras cerrar nóminas debe prepararse la comunicación de Conceptos Retributivos Abonados.",
        inputs=["Nóminas", "Conceptos retributivos", "Periodo", "Códigos CRA"],
        expected_actions=["Generar fichero CRA", "Revisar conceptos", "Corregir validaciones"],
        criteria=["Trabajadores y periodo correctos", "Conceptos comunicados sin omisiones relevantes", "Fichero validable"],
        theory=["Conceptos Retributivos Abonados", "Relación entre nómina y comunicación CRA"],
        feedback=["Parte de lo realmente abonado en nómina", "Revisa el tratamiento CRA de cada concepto antes de reenviar"],
    ),
    "A34": _spec(
        "Interpretar una liquidación de cuotas y relacionar RNT y RLC con la información de nómina.",
        prerequisites=["A18", "A20"],
        situation="La liquidación mensual está preparada y debe revisarse antes de confirmarla.",
        inputs=["Relación nominal de trabajadores", "Recibo de liquidación", "Nóminas", "Bases y cuotas"],
        expected_actions=["Revisar RNT", "Revisar RLC", "Cuadrar trabajadores y totales"],
        criteria=["Plantilla liquidada correcta", "Bases y cuotas coherentes", "Total RLC compatible con el detalle"],
        theory=["Sistema de Liquidación Directa", "RNT y RLC"],
        feedback=["Empieza por comprobar qué trabajadores contiene la liquidación", "Después contrasta bases y total de cuotas"],
    ),
    "A35": _spec(
        "Resolver un ciclo simulado de envío SILTRA incluyendo error, corrección y reenvío.",
        prerequisites=["A34", "A33"],
        situation="Una remesa recibe una respuesta con error y debe subsanarse antes de quedar aceptada.",
        inputs=["Fichero a enviar", "Respuesta SILTRA", "Código o descripción del error", "Datos origen"],
        expected_actions=["Enviar remesa", "Interpretar respuesta", "Corregir origen", "Reenviar"],
        criteria=["Error identificado", "Corrección aplicada al dato origen", "Segundo envío aceptado"],
        theory=["SILTRA", "Intercambio de ficheros y respuestas en Sistema RED"],
        feedback=["No corrijas solo el fichero generado", "Localiza el dato de origen que provoca la respuesta y vuelve a generar"],
    ),
    "A36": _spec(
        "Registrar las circunstancias personales y familiares que el trabajador comunica al pagador mediante Modelo 145.",
        prerequisites=["A04"],
        situation="Un trabajador entrega su Modelo 145 y debe actualizarse su perfil fiscal.",
        inputs=["Modelo 145", "Situación familiar", "Descendientes/ascendientes", "Otros datos comunicados"],
        expected_actions=["Registrar perfil fiscal", "Vincular documento", "Dejar trazabilidad de la comunicación"],
        criteria=["Datos fiscales coinciden con el documento", "Documento asociado", "Perfil listo para calcular retención"],
        theory=["Modelo 145", "Comunicación de datos al pagador"],
        feedback=["No deduzcas circunstancias no comunicadas", "Traslada únicamente los datos respaldados por el Modelo 145"],
    ),
    "A37": _spec(
        "Calcular el tipo de retención sobre rendimientos del trabajo utilizando parámetros 2026.",
        prerequisites=["A36"],
        situation="Debe determinarse el tipo de retención aplicable antes de calcular las nóminas del ejercicio.",
        inputs=["Retribución prevista", "Perfil fiscal", "Datos del contrato", "Parámetros AEAT 2026"],
        expected_actions=["Calcular tipo", "Revisar resultado", "Guardar porcentaje aplicable"],
        criteria=["Cálculo reproducible", "Porcentaje coincide con motor 2026", "Perfil utilizado correcto"],
        theory=["Procedimiento de cálculo de retenciones", "Rendimientos del trabajo"],
        feedback=["Comprueba retribución anual prevista y situación familiar", "Evita reutilizar porcentajes de ejercicios anteriores"],
    ),
    "A38": _spec(
        "Regularizar una retención cuando cambian las circunstancias relevantes durante el ejercicio.",
        prerequisites=["A37"],
        situation="Un cambio personal o retributivo obliga a recalcular el tipo para los periodos restantes.",
        inputs=["Tipo anterior", "Nueva circunstancia", "Retribuciones satisfechas", "Retribución pendiente"],
        expected_actions=["Actualizar datos", "Regularizar tipo", "Aplicar nuevo porcentaje en nómina"],
        criteria=["Motivo de regularización identificado", "Nuevo tipo calculado", "Aplicación desde el periodo correcto"],
        theory=["Regularización de retenciones", "Cambios personales y retributivos"],
        feedback=["No recalcules como si el ejercicio empezara de cero", "Ten en cuenta lo ya satisfecho y retenido"],
    ),
    "A39": _spec(
        "Registrar un profesional sujeto a retención y conectarlo con las obligaciones del retenedor.",
        prerequisites=["A37"],
        situation="La empresa abona servicios profesionales que deben formar parte de sus declaraciones de retenciones.",
        inputs=["Profesional", "NIF", "Importe", "Tipo de retención", "Fecha"],
        expected_actions=["Crear perceptor profesional", "Registrar rendimiento y retención", "Incluirlo en periodo fiscal"],
        criteria=["Perceptor identificado", "Base y retención correctas", "Dato disponible para 111/190"],
        theory=["Retenciones de actividades económicas", "Obligaciones del retenedor"],
        feedback=["No mezcles al profesional con un trabajador en nómina", "Comprueba base y tipo antes de cerrar el periodo"],
    ),
    "A40": _spec(
        "Generar y revisar una autoliquidación Modelo 111 a partir de retenciones del periodo.",
        prerequisites=["A21", "A39"],
        situation="Finaliza el periodo de liquidación y deben declararse las retenciones practicadas.",
        inputs=["Nóminas", "Profesionales", "Bases", "Retenciones", "Periodo"],
        expected_actions=["Generar Modelo 111", "Revisar perceptores e importes", "Presentar de forma simulada"],
        criteria=["Periodo correcto", "Bases y retenciones cuadran con origen", "Estado presentado simulado"],
        theory=["Modelo 111", "Autoliquidación de retenciones e ingresos a cuenta"],
        feedback=["Cuadra primero los importes con nóminas y profesionales", "Revisa el periodo antes de presentar"],
    ),
    "A41": _spec(
        "Generar el resumen anual Modelo 190 y cuadrarlo con perceptores y declaraciones periódicas.",
        prerequisites=["A40"],
        situation="Al cierre del ejercicio debe prepararse el resumen anual de retenciones.",
        inputs=["Perceptores del ejercicio", "Bases y retenciones anuales", "Modelos 111", "Claves fiscales"],
        expected_actions=["Generar Modelo 190", "Revisar perceptores", "Cuadrar totales anuales"],
        criteria=["Todos los perceptores esperados", "Importes anuales coherentes", "Cuadre razonable con declaraciones periódicas"],
        theory=["Modelo 190", "Resumen anual de retenciones"],
        feedback=["Comprueba primero el censo de perceptores", "Después revisa acumulados y su correspondencia con el ejercicio"],
    ),
    "A42": _spec(
        "Corregir un concepto salarial erróneo preservando el cálculo original y la causa del cambio.",
        prerequisites=["A14", "A16"],
        situation="Se detecta que una nómina se calculó con un importe salarial incorrecto.",
        inputs=["Concepto original", "Importe correcto", "Periodo afectado", "Motivo"],
        expected_actions=["Corregir estructura salarial", "Recalcular", "Generar diferencia"],
        criteria=["Concepto actualizado", "Periodo recalculado", "Diferencia trazable"],
        theory=["Regularización salarial", "Trazabilidad de cálculos"],
        feedback=["Corrige primero la causa permanente", "Después genera la diferencia sobre el periodo afectado"],
    ),
    "A43": _spec(
        "Regularizar un complemento de antigüedad con efectos retroactivos.",
        prerequisites=["A42"],
        situation="Una fecha de antigüedad reconocida no se tuvo en cuenta y genera diferencias en nóminas anteriores.",
        inputs=["Fecha de antigüedad", "Regla del complemento", "Periodos afectados", "Nóminas originales"],
        expected_actions=["Revisar contrato", "Activar/corregir complemento", "Recalcular y regularizar"],
        criteria=["Fecha correcta", "Complemento activo", "Diferencia generada para los periodos correspondientes"],
        theory=["Antigüedad", "Efectos retroactivos y diferencias salariales"],
        feedback=["Empieza por la fecha reconocida", "No regularices periodos anteriores a la fecha de efectos"],
    ),
    "A44": _spec(
        "Generar atrasos derivados de una revisión salarial con fecha de efectos anterior.",
        prerequisites=["A42", "A03"],
        situation="Un convenio o revisión salarial se publica con efectos económicos retroactivos.",
        inputs=["Tabla anterior", "Nueva tabla", "Fecha de efectos", "Periodos ya pagados"],
        expected_actions=["Actualizar valores", "Identificar periodos", "Generar atrasos"],
        criteria=["Nueva tabla aplicada desde fecha correcta", "Solo periodos afectados", "Diferencias acumuladas correctamente"],
        theory=["Revisión salarial", "Atrasos de convenio"],
        feedback=["Distingue fecha de publicación y fecha de efectos", "Calcula diferencias periodo a periodo"],
    ),
    "A45": _spec(
        "Explicar una regularización comparando cálculo original, causa y resultado corregido.",
        prerequisites=["A42"],
        situation="Auditoría interna solicita justificar por qué una nómina ha cambiado después de su cálculo inicial.",
        inputs=["Nómina original", "Regularización", "Motivo", "Nuevos importes"],
        expected_actions=["Comparar versiones", "Identificar líneas afectadas", "Justificar diferencia"],
        criteria=["Origen y resultado diferenciados", "Motivo documentado", "Importes de diferencia cuadran"],
        theory=["Trazabilidad de regularizaciones", "Evidencia de cálculo"],
        feedback=["No describas solo el resultado final", "Explica qué cambió, desde cuándo y qué diferencia genera"],
    ),
    "A46": _spec(
        "Tramitar administrativamente una baja voluntaria coordinando contrato, afiliación y expediente.",
        prerequisites=["A30"],
        situation="La persona trabajadora comunica su decisión de finalizar la relación laboral.",
        inputs=["Comunicación de baja", "Fecha de efectos", "Contrato", "Vacaciones pendientes"],
        expected_actions=["Registrar motivo de extinción", "Finalizar contrato", "Preparar baja de afiliación", "Abrir liquidación final"],
        criteria=["Motivo correcto", "Fecha coherente", "Contrato finalizado", "Baja preparada"],
        theory=["Extinción por voluntad del trabajador", "Coordinación administrativa del cese"],
        feedback=["La baja voluntaria es un motivo de extinción específico", "Alinea la misma fecha en contrato y afiliación"],
    ),
    "A47": _spec(
        "Tramitar el fin de un contrato temporal y distinguir sus efectos de otros ceses.",
        prerequisites=["A08", "A30"],
        situation="Un contrato de duración determinada llega a su fecha de finalización.",
        inputs=["Contrato temporal", "Fecha fin", "Causa", "Datos de liquidación"],
        expected_actions=["Registrar expiración", "Finalizar contrato", "Preparar baja", "Calcular efectos finales"],
        criteria=["Motivo expiración seleccionado", "Fecha coincide con contrato", "No se registra como baja voluntaria o despido"],
        theory=["Expiración del tiempo convenido", "Efectos indemnizatorios cuando procedan"],
        feedback=["Revisa el motivo jurídico del cese", "Comprueba si la modalidad del contrato genera indemnización por finalización"],
    ),
    "A48": _spec(
        "Registrar un despido disciplinario y dejar evidencia documental básica del proceso simulado.",
        prerequisites=["A46"],
        situation="La empresa comunica una extinción disciplinaria con efectos en una fecha determinada.",
        inputs=["Trabajador", "Fecha", "Motivo/carta simulada", "Contrato"],
        expected_actions=["Registrar extinción disciplinaria", "Vincular documentación", "Preparar baja"],
        criteria=["Motivo correcto", "Fecha coherente", "Documento de comunicación asociado"],
        theory=["Despido disciplinario", "Comunicación escrita como documentación del supuesto"],
        feedback=["No confundas el motivo de extinción", "Comprueba que la documentación pertenece al trabajador y fecha del caso"],
    ),
    "A49": _spec(
        "Registrar una extinción con indemnización y comprender los parámetros que determinan su cálculo.",
        prerequisites=["A47", "A48"],
        situation="Un supuesto de extinción genera derecho a una indemnización que debe calcularse y documentarse.",
        inputs=["Motivo", "Antigüedad", "Salario regulador del caso", "Fecha de efectos"],
        expected_actions=["Seleccionar motivo", "Calcular indemnización", "Incorporar resultado a la liquidación"],
        criteria=["Regla de indemnización asociada al motivo", "Antigüedad y salario utilizados coherentes", "Importe trazable"],
        theory=["Indemnizaciones por extinción", "Salario y tiempo de servicio en el cálculo"],
        feedback=["La indemnización depende del motivo de extinción", "Revisa antigüedad y salario regulador antes de calcular"],
    ),
    "A50": _spec(
        "Calcular una liquidación final separando salario pendiente, pagas, vacaciones e indemnización cuando exista.",
        prerequisites=["A46", "A15"],
        situation="Tras registrar el cese debe confeccionarse el finiquito del trabajador.",
        inputs=["Fecha de cese", "Salario pendiente", "Pagas extraordinarias", "Vacaciones no disfrutadas", "Indemnización si procede"],
        expected_actions=["Calcular conceptos finales", "Generar finiquito", "Revisar total"],
        criteria=["Conceptos separados", "Periodos proporcionales correctos", "Indemnización no se confunde con salario"],
        theory=["Liquidación/finiquito", "Conceptos pendientes al extinguir la relación"],
        feedback=["Desglosa cada concepto antes de sumar", "Comprueba vacaciones y pagas devengadas hasta la fecha de cese"],
    ),
    "A51": _spec(
        "Preparar un checklist documental mínimo para una incorporación laboral.",
        prerequisites=["A04", "A07"],
        situation="El trabajador está contratado y debe comprobarse que el expediente reúne la documentación inicial prevista.",
        inputs=["Tipo de incorporación", "Documentos disponibles", "Documentos requeridos"],
        expected_actions=["Generar checklist", "Marcar recibidos y pendientes", "Relacionar documentos con expediente"],
        criteria=["Checklist completo", "Estados coherentes", "Sin documentos críticos omitidos"],
        theory=["Archivo de documentación laboral", "Expediente de incorporación"],
        feedback=["Revisa qué documentos exige este proceso concreto", "No marques como recibido un documento que no existe en el expediente"],
    ),
    "A52": _spec(
        "Resolver un expediente documental distinguiendo pendiente, recibido, caducado y no aplicable.",
        prerequisites=["A51"],
        situation="Una revisión de expedientes detecta documentación en distintos estados que debe regularizarse.",
        inputs=["Listado documental", "Fechas", "Evidencias", "Reglas del caso"],
        expected_actions=["Filtrar documentos", "Actualizar estados", "Cerrar pendientes justificables"],
        criteria=["Estado de cada documento coherente", "Caducidades identificadas", "No aplicable justificado"],
        theory=["Estados documentales", "Conservación y evidencia"],
        feedback=["El estado debe corresponder a la evidencia disponible", "Comprueba las fechas antes de tratar un documento como vigente"],
    ),
    "A53": _spec(
        "Responder a una solicitud laboral mediante una comunicación profesional basada en el expediente.",
        prerequisites=["A04"],
        situation="RRHH recibe un correo que exige comprobar datos y responder con una actuación concreta.",
        inputs=["Hilo de correo", "Expediente", "Documentos relacionados", "Resultado de la gestión"],
        expected_actions=["Interpretar solicitud", "Realizar comprobación necesaria", "Responder en el mismo hilo"],
        criteria=["Respuesta enviada", "Contenido coherente con el expediente", "No inventa datos ausentes"],
        theory=["Comunicación profesional", "Trazabilidad entre solicitud y actuación"],
        feedback=["Responde a lo solicitado, no a un supuesto distinto", "Comprueba el expediente antes de afirmar que una gestión está realizada"],
    ),
    "A54": _spec(
        "Localizar las evidencias que permiten reconstruir un proceso laboral ya terminado.",
        prerequisites=["A51", "A53"],
        situation="Una revisión docente o auditoría interna solicita demostrar qué se hizo y con qué documentación.",
        inputs=["Proceso finalizado", "Documentos", "Correos", "Registros del ERP"],
        expected_actions=["Localizar evidencias", "Relacionarlas con el proceso", "Justificar el cierre"],
        criteria=["Evidencias pertenecen al proceso", "Secuencia comprensible", "No quedan huecos críticos sin justificar"],
        theory=["Trazabilidad", "Archivo y evidencia de gestión"],
        feedback=["Busca evidencias del origen, ejecución y resultado", "Un documento aislado no siempre demuestra el proceso completo"],
    ),
    "C01": _spec(
        "Resolver una incorporación completa integrando expediente, contrato, afiliación, documentación y primera nómina.",
        prerequisites=["A04", "A07", "A29", "A51", "A16"],
        situation="Dirección comunica una nueva incorporación y aporta la documentación necesaria sin enumerar los pasos administrativos.",
        inputs=["Correo de incorporación", "Datos personales", "Condiciones del puesto", "Convenio", "Fecha de inicio"],
        expected_actions=["Crear expediente", "Asignar estructura", "Formalizar contrato", "Preparar alta", "Completar documentos", "Calcular primera nómina"],
        criteria=["Secuencia completa", "Datos coherentes entre módulos", "Primera nómina calculada sobre la relación creada"],
        theory=["Flujo completo de contratación", "Dependencias entre expediente, contrato, afiliación y nómina"],
        feedback=["Revisa qué paso previo alimenta al siguiente", "Si un resultado falla, vuelve al dato de origen antes de repetir toda la secuencia"],
    ),
    "C02": _spec(
        "Gestionar una baja médica con sustitución y coordinar titular, sustituta, FIE, afiliación y nóminas.",
        prerequisites=["A23", "A09", "A29", "A31", "A32"],
        situation="Se recibe una comunicación médica y simultáneamente se autoriza la contratación de una sustituta.",
        inputs=["FIE", "Titular", "Datos de sustituta", "Fecha de inicio", "Condiciones contractuales"],
        expected_actions=["Conciliar IT", "Crear sustituta", "Crear contrato de sustitución", "Preparar alta", "Recalcular nóminas"],
        criteria=["Titular y sustituta no se confunden", "Fechas coordinadas", "Ambas situaciones reflejadas en nómina"],
        theory=["IT y sustitución", "Coordinación de procesos concurrentes"],
        feedback=["Separa primero el expediente de la titular y el de la sustituta", "Después verifica que las fechas se solapan de forma coherente"],
    ),
    "C03": _spec(
        "Investigar una reclamación salarial, corregir la causa y generar el retroactivo justificable.",
        prerequisites=["A43", "A45", "A53"],
        situation="Una trabajadora reclama que no se le ha abonado correctamente la antigüedad.",
        inputs=["Correo de reclamación", "Contrato", "Fecha de antigüedad", "Nóminas", "Regla salarial"],
        expected_actions=["Investigar", "Corregir concepto", "Regularizar periodos", "Responder al correo"],
        criteria=["Causa identificada", "Retroactivo correcto", "Respuesta coincide con la solución aplicada"],
        theory=["Reclamación y trazabilidad", "Regularización por antigüedad"],
        feedback=["No regularices hasta localizar la causa", "La respuesta final debe poder justificarse con los cálculos del expediente"],
    ),
    "C04": _spec(
        "Cerrar un periodo fiscal integrando retenciones de trabajadores y profesionales en el Modelo 111.",
        prerequisites=["A37", "A39", "A40"],
        situation="Finaliza el trimestre y contabilidad solicita la declaración de retenciones con todos los perceptores incluidos.",
        inputs=["Nóminas del trimestre", "Profesionales", "Perfiles fiscales", "Retenciones practicadas"],
        expected_actions=["Revisar perceptores", "Corregir inconsistencias", "Generar y presentar 111 simulado"],
        criteria=["Trabajadores y profesionales incluidos", "Bases y retenciones cuadradas", "Periodo correcto"],
        theory=["Obligaciones del retenedor", "Modelo 111"],
        feedback=["Comprueba el origen de cada importe", "Un perceptor ausente puede descuadrar la declaración aunque el total de nóminas sea correcto"],
    ),
    "C05": _spec(
        "Resolver un cierre de cotización con error desde CRA/RNT-RLC hasta la corrección y reenvío por SILTRA simulado.",
        prerequisites=["A33", "A34", "A35"],
        situation="La remesa de cotización recibe una respuesta de error que obliga a revisar los datos del trabajador o concepto afectado.",
        inputs=["CRA", "RNT", "RLC", "Respuesta SILTRA", "Nóminas origen"],
        expected_actions=["Identificar discrepancia", "Corregir dato origen", "Regenerar", "Reenviar y validar"],
        criteria=["Corrección realizada en origen", "Nueva liquidación coherente", "Remesa final aceptada"],
        theory=["Sistema de Liquidación Directa", "SILTRA y corrección de errores"],
        feedback=["La respuesta indica dónde investigar, no qué dato inventar", "Cuadra de nuevo RNT/RLC después de corregir el origen"],
    ),
    "C06": _spec(
        "Resolver una extinción completa coordinando cese, baja, liquidación final, documentación y comunicación.",
        prerequisites=["A46", "A49", "A50", "A53"],
        situation="Se comunica el fin de una relación laboral y RRHH debe ejecutar todo el cierre administrativo.",
        inputs=["Motivo de extinción", "Fecha", "Contrato", "Vacaciones", "Pagas", "Documentación"],
        expected_actions=["Registrar extinción", "Preparar baja", "Calcular finiquito e indemnización si procede", "Generar documentación", "Comunicar cierre"],
        criteria=["Motivo y fecha coherentes", "Liquidación completa", "Baja coordinada", "Evidencia documental suficiente"],
        theory=["Extinción y liquidación final", "Trazabilidad del cese"],
        feedback=["Comprueba primero el motivo porque condiciona el resto", "No cierres el expediente hasta cuadrar contrato, afiliación y liquidación"],
    ),
}


def activity_spec(code: str) -> dict[str, Any]:
    return ACTIVITY_SPECS_2026[code]
