"""Fuentes oficiales de referencia para el Temario Maestro AulaNomina 2026.

Este registro no sustituye la verificación jurídica previa a publicar contenido.
Cada fuente indica la fecha de revisión usada para diseñar el curso. Los módulos
que dependan de parámetros anuales deben volver a contrastarse al cambiar de
ejercicio.
"""

OFFICIAL_SOURCES_2026 = {
    "FP_AF_RD_1584_2011": {
        "title": "Título de Técnico Superior en Administración y Finanzas",
        "issuer": "BOE / Ministerio de Educación",
        "reference": "Real Decreto 1584/2011, de 4 de noviembre",
        "url": "https://www.boe.es/eli/es/rd/2011/11/04/1584",
        "checked_on": "2026-08-14",
        "scope": "Resultados de aprendizaje y contenidos mínimos del módulo 0652 Gestión de recursos humanos.",
        "update_policy": "stable_curriculum",
    },
    "ET_RDL_2_2015": {
        "title": "Estatuto de los Trabajadores",
        "issuer": "BOE",
        "reference": "Real Decreto Legislativo 2/2015, de 23 de octubre",
        "url": "https://www.boe.es/buscar/act.php?id=BOE-A-2015-11430",
        "checked_on": "2026-08-14",
        "scope": "Relación laboral, contratación, salario, jornada, modificación, suspensión y extinción.",
        "update_policy": "verify_before_release",
    },
    "LGSS_RDL_8_2015": {
        "title": "Ley General de la Seguridad Social",
        "issuer": "BOE",
        "reference": "Real Decreto Legislativo 8/2015, de 30 de octubre",
        "url": "https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724",
        "checked_on": "2026-08-14",
        "scope": "Afiliación, cotización, recaudación, prestaciones e incapacidad temporal.",
        "update_policy": "verify_before_release",
    },
    "COT_PJC_297_2026": {
        "title": "Normas de cotización a la Seguridad Social para 2026",
        "issuer": "BOE",
        "reference": "Orden PJC/297/2026, de 30 de marzo",
        "url": "https://www.boe.es/eli/es/o/2026/03/30/pjc297",
        "checked_on": "2026-08-14",
        "scope": "Bases, topes, tipos y reglas de cotización del ejercicio 2026 para el Régimen General.",
        "update_policy": "annual",
    },
    "CONTRATOS_FORMATIVOS_RD_1065_2025": {
        "title": "Régimen del contrato formativo",
        "issuer": "BOE / Ministerio de Trabajo y Economía Social",
        "reference": "Real Decreto 1065/2025, de 26 de noviembre",
        "url": "https://www.boe.es/eli/es/rd/2025/11/26/1065",
        "checked_on": "2026-08-14",
        "scope": "Formación en alternancia y contrato para la obtención de práctica profesional.",
        "update_policy": "verify_before_release",
    },
    "SEPE_CONTRATOS": {
        "title": "Modalidades y modelos oficiales de contratos",
        "issuer": "SEPE",
        "reference": "Modalidades de contratos de trabajo",
        "url": "https://www.sepe.es/HomeSepe/empresas/Contratos-de-trabajo/modelos-contrato.html",
        "checked_on": "2026-08-14",
        "scope": "Modelos vigentes: indefinido, temporal, formación en alternancia y práctica profesional. La duración determinada se articula por circunstancias de la producción o sustitución.",
        "update_policy": "verify_before_release",
    },
    "TGSS_RED": {
        "title": "Sistema RED",
        "issuer": "Tesorería General de la Seguridad Social",
        "reference": "Portal Sistema RED",
        "url": "https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/",
        "checked_on": "2026-08-14",
        "scope": "Afiliación, Sistema de Liquidación Directa, SILTRA, Noticias RED y comunicaciones profesionales.",
        "update_policy": "frequent",
    },
    "TGSS_SLD": {
        "title": "Sistema de Liquidación Directa",
        "issuer": "Tesorería General de la Seguridad Social",
        "reference": "Portal del Sistema de Liquidación Directa",
        "url": "https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/2837/",
        "checked_on": "2026-08-14",
        "scope": "Proceso telemático de liquidación de cuotas, contraste previo de datos y documentación asociada a la liquidación.",
        "update_policy": "frequent",
    },
    "TGSS_SILTRA_4_2026": {
        "title": "SILTRA 4.0.0",
        "issuer": "Tesorería General de la Seguridad Social",
        "reference": "Publicación nueva versión SILTRA 4.0.0, 01/06/2026",
        "url": "https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/3827/e8dafb74-f2f2-43fe-a8e1-9be3c10c6486/nueva%2Bversion%2Bsiltra%2B4.0.0.",
        "checked_on": "2026-08-14",
        "scope": "Referencia de versión del cliente SILTRA vigente para los escenarios simulados de envío y respuesta en 2026.",
        "update_policy": "frequent",
    },
    "TGSS_FIE_5_2026": {
        "title": "Fichero INSS Empresas 5.0",
        "issuer": "Seguridad Social / Sistema RED",
        "reference": "Nueva versión FIE 5.0, entrada en funcionamiento 16/06/2026",
        "url": "https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/3827/e8dafb74-f2f2-43fe-a8e1-9be3c10c6486",
        "checked_on": "2026-08-14",
        "scope": "Recepción e interpretación de comunicaciones FIE en 2026.",
        "update_policy": "frequent",
    },
    "TGSS_CRA_2026": {
        "title": "Conceptos Retributivos Abonados (CRA)",
        "issuer": "Tesorería General de la Seguridad Social",
        "reference": "Manual CRA publicado 13/07/2026",
        "url": "https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/2867",
        "checked_on": "2026-08-14",
        "scope": "Comunicación, validaciones y tratamiento de conceptos retributivos abonados.",
        "update_policy": "frequent",
    },
    "AEAT_RETENCIONES_2026": {
        "title": "Retenciones IRPF 2026",
        "issuer": "Agencia Estatal de Administración Tributaria",
        "reference": "Servicio y algoritmo de cálculo de retenciones 2026",
        "url": "https://sede.agenciatributaria.gob.es/Sede/Retenciones.shtml",
        "checked_on": "2026-08-14",
        "scope": "Cálculo del tipo de retención sobre rendimientos del trabajo en 2026 y especificaciones técnicas oficiales.",
        "update_policy": "annual",
    },
    "AEAT_MODELO_145": {
        "title": "Modelo 145",
        "issuer": "Agencia Estatal de Administración Tributaria",
        "reference": "Comunicación de datos al pagador",
        "url": "https://sede.agenciatributaria.gob.es/Sede/procedimientos/G603.shtml",
        "checked_on": "2026-08-14",
        "scope": "Datos personales y familiares comunicados al pagador para practicar retenciones.",
        "update_policy": "verify_before_release",
    },
    "AEAT_MODELO_111": {
        "title": "Modelo 111",
        "issuer": "Agencia Estatal de Administración Tributaria",
        "reference": "Retenciones e ingresos a cuenta. Autoliquidación",
        "url": "https://sede.agenciatributaria.gob.es/Sede/irpf/retenciones-ingresos-cuenta-pagos-fraccionados/retenciones-ingresos-cuenta/obligaciones-retenedor/modelo-111.html",
        "checked_on": "2026-08-14",
        "scope": "Autoliquidación periódica de retenciones e ingresos a cuenta sobre rendimientos del trabajo y determinadas actividades económicas, entre otras rentas.",
        "update_policy": "verify_before_release",
    },
    "AEAT_MODELO_190": {
        "title": "Modelo 190",
        "issuer": "Agencia Estatal de Administración Tributaria",
        "reference": "Resumen anual de retenciones e ingresos a cuenta",
        "url": "https://sede.agenciatributaria.gob.es/Sede/irpf/retenciones-ingresos-cuenta-pagos-fraccionados/retenciones-ingresos-cuenta/obligaciones-retenedor/modelo-190.html",
        "checked_on": "2026-08-14",
        "scope": "Resumen anual de rendimientos del trabajo y determinadas actividades económicas, premios y otras rentas incluidas en el modelo.",
        "update_policy": "annual",
    },
}
